- name: Set kernel params to /etc/sysctl.d/
  copy:
    src: files/k8s-kernel-params.conf
    dest: /etc/sysctl.d/k8s-kernel-params.conf

- name: Adjust kernel params
  command: "sysctl -p /etc/sysctl.d/k8s-kernel-params.conf"
  register: kernel_params_result

- name: Print kernel params result
  debug:
    var: kernel_params_result