- name: Temporarily shutdown selinux
  shell: "setenforce 0"
  when: 
    - (ansible_facts['os_family'] == 'RedHat')

- name: Permanent shutdown selinux
  shell: "sed -i 's/^SELINUX=enforcing/SELINUX=disabled/' /etc/selinux/config"
  when: 
    - (ansible_facts['os_family'] == 'RedHat')